hw17 new edits

diff --git a/hw17/Vagrantfile b/hw17/Vagrantfile
--- a/hw17/Vagrantfile
+++ b/hw17/Vagrantfile
@@ -51,6 +51,36 @@ Vagrant.configure("2") do |config|
               usermod -a -G admin pamuser
               echo "pamuser:pamuser" | chpasswd
               sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
+              echo "auth       required     pam_script.so" >> /etc/pam.d/sshd
+              cat <<'EOT' > /etc/pam_script
+#!/bin/bash
+
+# Check if User in "admin" group
+USER=$PAM_USER
+
+if [[ `grep $USER /etc/group | grep 'admin'` ]]
+then
+  exit 1
+fi
+
+# Check if today is free day or a holiday.
+DAY=`date +"%u"`
+MDAY=`date +"%d%m"`
+
+if [[ $DAY == "6" || $DAY == "7" ]]
+then
+  echo "Hey, it's weekend! Go home!"
+  exit 1
+elif [[ $MDAY == "0101" || $MDAY == "0803" || $MDAY == "2302" ]]
+then
+  echo "Hey! Today is holiday! Go HOME!"
+  exit 1
+else
+  echo "OK, today's work day. Go and work!"
+  exit 0
+fi
+EOT
+              chmod +x /etc/pam_script
               systemctl restart sshd
             SHELL
         end
